### ISSUE TITLE
Implement the Storybook

### ISSUE THREAD

**Issue by chin8628** [it-kmitl-2018/group3-frontend#12]
https://github.com/storybooks/storybook

**Comment by champillon** [comment]
แม่เจ้า!!!

**Comment by chin8628** [comment]
@champillon มีอะไรหรือเปล่าครับ 55555

**Comment by champillon** [comment]
เท่ห์ดี เผื่อลอกไปใช้ 5555555555

**Comment by chin8628** [comment]
คิดค่าไอเดีย 5 คะแนนครับ 5555

**Comment by champillon** [comment]
Noooooooo this is opensourceeeeeeeeee !!!!!!

**Comment by chin8628** [comment]
merged. #14
