### ISSUE TITLE
Versioning & GIT convention

### ISSUE THREAD

**Issue by Chiibi** [it-kmitl-2018/group3-frontend#3]
Should we have versioning, git commit style guide or anything that necessary in [CONVENTION.md](https://github.com/it-kmitl-2018/group3-frontend/blob/master/CONVENTION.md)? @XIIKJIIX

**Comment by XIIKJIIX** [comment]
It's good to have versioning convention. I saw a version attribute in `package.json` but I don't know the best practice. Any idea on it?
