### ISSUE TITLE
ข้อสงสัยใน requirement ของ flow diagram

### ISSUE THREAD

**Issue by chin8628** [it-kmitl-2018/group3-frontend#6]
@champillon อิงจากเอกสารความต้องการ จริง ๆ แล้วงานที่ทำต้องเป็นระบบทั้งระบบที่ต้องเก็บข้อมูล state ของผู้ซื้อผู้ขายทั้งหมด มี auth หรือว่าเป็นระบบที่ Provide แค่ api สำหรับ generate ข้อมูล xml แค่นั้นครับ

ขอบคุณครับ

**Comment by champillon** [comment]
กำ ฟังโจทย์อีกครั้ง

โดยจะให้นำ requirement นี้ทำเป็น web application 3 หน้าดังนี้ครับ
Page-1 หน้าเว็ปสำหรับกรอกข้อมูล
Page-2 หน้าเว็ปสำหรับยืนยันข้อมูล
Page-3 หน้าเว็ปสำหรับแสดง XML ที่ถูกสร้างจากข้อมูล ตาม format ของ สำนักงานธุรกรรมอิเล็กทรอนิกส์ (ETDA)

ดังนั้น เป็นแค่หน้าเว็ป 3 หน้า 
- ไม่ได้บอกว่าต้องทำเป็น API นะ
- ไม่ได้บอกว่าต้องมีการเก็บ state นะ
- ไม่ได้บอกว่า ต้องมีการ authentication นะ

แต่ถ้าอยากทำมา ก็ review ให้ได้ครับ

**Comment by XIIKJIIX** [comment]
@champillon พอมีตัวอย่าง XML ของใบแจ้งหนี้และใบรับ electronics มั้ยครับ

**Comment by champillon** [comment]
@XIIKJIIX อันนี้ลืมบอกไป ออกแต่ "ใบกำกับภาษีอิเล็กทรอนิกส์" ครับ ซึ่ง XML อยู่ในเอกสารของ ETDA ที่แปะใน facebook group หน้า 54
